import type { Metadata } from "next";
import { Inter,Loved_by_the_King} from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const king = Loved_by_the_King({subsets:["latin"],weight:'400'})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={king.className}>{children}</body>
    </html>
  );
}
